#ifndef CVL_TPL_MAKEFILE_H
#define CVL_TPL_MAKEFILE_H

static const char *TPL_MAKEFILE =
"PROGRAM   := %s\n"
"SRC_DIR   := src\n"
"BUILD_DIR := build\n"
"\n"
"# set CARAVEL_INCLUDE env var or adjust here\n"
"CARAVEL_INCLUDE ?= ../../include\n"
"\n"
"# set CLANG/LLD env vars to override\n"
"CLANG ?= $(HOME)/.cache/solana/v1.51/platform-tools/llvm/bin/clang\n"
"LLD   ?= $(HOME)/.cache/solana/v1.51/platform-tools/llvm/bin/ld.lld\n"
"\n"
"CFLAGS  := --target=sbf -fPIC -O2 -fno-builtin -I$(CARAVEL_INCLUDE)\n"
"LDFLAGS := -z notext -shared --Bdynamic $(CARAVEL_INCLUDE)/bpf.ld --entry entrypoint\n"
"\n"
"SRCS := $(wildcard $(SRC_DIR)/*.c)\n"
"OBJS := $(patsubst $(SRC_DIR)/%%.c,$(BUILD_DIR)/%%.o,$(SRCS))\n"
"SO   := $(BUILD_DIR)/program.so\n"
"\n"
".PHONY: all build clean test deploy\n"
"\n"
"all: build\n"
"\n"
"build: $(SO)\n"
"\t@echo \"  Build complete: $(SO)\"\n"
"\n"
"$(BUILD_DIR)/%%.o: $(SRC_DIR)/%%.c | $(BUILD_DIR)\n"
"\t$(CLANG) $(CFLAGS) -c $< -o $@\n"
"\n"
"$(SO): $(OBJS)\n"
"\t$(LLD) $(LDFLAGS) -o $@ $^\n"
"\n"
"$(BUILD_DIR):\n"
"\tmkdir -p $(BUILD_DIR)\n"
"\n"
"clean:\n"
"\trm -rf $(BUILD_DIR)\n"
"\n"
"test: build\n"
"\tcd tests && npm install && npm test\n"
"\n"
"deploy: build\n"
"\tsolana program deploy $(SO)\n";

#endif /* CVL_TPL_MAKEFILE_H */
