#ifndef TPL_MAKEFILE_H
#define TPL_MAKEFILE_H

static const char *TPL_MAKEFILE =
"PROGRAM   := %s\n"
"SRC_DIR   := src\n"
"BUILD_DIR := build\n"
"\n"
"SBF_VER ?= %s\n"
"\n"
"# set CARAVEL_INCLUDE env var or adjust here\n"
"CARAVEL_INCLUDE ?= $(HOME)/.local/share/caravel/include\n"
"\n"
"# newest installed platform-tools; set CLANG/LLD env vars to override\n"
"PT    ?= $(shell ls -d $(HOME)/.cache/solana/v*/platform-tools 2>/dev/null | sort -V | tail -1)\n"
"CLANG ?= $(PT)/llvm/bin/clang\n"
"LLD   ?= $(PT)/llvm/bin/ld.lld\n"
"\n"
"# per-version toolchain flags\n"
"ifeq ($(SBF_VER),v3)\n"
"  ARCH    := -mcpu=v3 -DCVL_STATIC_SYSCALLS\n"
"  SCRIPT  := sbpfv3.ld\n"
"  LDEXTRA := --strip-all -Bsymbolic\n"
"else ifeq ($(SBF_VER),v2)\n"
"  ARCH    := -mcpu=v2\n"
"  SCRIPT  := bpf.ld\n"
"  LDEXTRA :=\n"
"else ifeq ($(SBF_VER),v1)\n"
"  ARCH    := -mcpu=v1\n"
"  SCRIPT  := bpf.ld\n"
"  LDEXTRA :=\n"
"else\n"
"  ARCH    :=\n"
"  SCRIPT  := bpf.ld\n"
"  LDEXTRA :=\n"
"endif\n"
"\n"
"CFLAGS  := --target=sbf $(ARCH) -fPIC -O2 -fno-builtin -I$(CARAVEL_INCLUDE)\n"
"LDFLAGS := -z notext -shared --Bdynamic --gc-sections $(LDEXTRA) $(CARAVEL_INCLUDE)/$(SCRIPT) --entry entrypoint\n"
"\n"
"SRCS := $(wildcard $(SRC_DIR)/*.c)\n"
"OBJS := $(patsubst $(SRC_DIR)/%%.c,$(BUILD_DIR)/%%.o,$(SRCS))\n"
"SO   := $(BUILD_DIR)/program.so\n"
"\n"
".PHONY: all build clean test deploy\n"
"\n"
"all: build\n"
"\n"
"build: $(SO)\n"
"\t@echo \"  Build complete: $(SO) ($(SBF_VER))\"\n"
"\n"
"$(BUILD_DIR)/%%.o: $(SRC_DIR)/%%.c\n"
"\t@mkdir -p $(BUILD_DIR)\n"
"\t$(CLANG) $(CFLAGS) -c $< -o $@\n"
"\n"
"$(SO): $(OBJS)\n"
"\t@mkdir -p $(BUILD_DIR)\n"
"\t$(LLD) $(LDFLAGS) -o $@ $^\n"
"\n"
"clean:\n"
"\trm -rf $(BUILD_DIR)\n"
"\n"
"test: build\n"
"\tcd tests && npm install && npm test\n"
"\n"
"deploy: build\n"
"\tsolana program deploy $(SO)\n";

#endif /* TPL_MAKEFILE_H */
