#ifndef CVL_TPL_TEST_H
#define CVL_TPL_TEST_H

static const char *TPL_PACKAGE_JSON =
"{\n"
"  \"name\": \"%s-tests\",\n"
"  \"version\": \"1.0.0\",\n"
"  \"description\": \"Tests for %s\",\n"
"  \"scripts\": {\n"
"    \"test\": \"npx ts-mocha -p ./tsconfig.json ./*.test.ts\"\n"
"  },\n"
"  \"dependencies\": {\n"
"    \"@solana/web3.js\": \"^1.95.0\",\n"
"    \"litesvm\": \"^0.3.0\",\n"
"    \"chai\": \"^4.3.7\",\n"
"    \"mocha\": \"^10.2.0\",\n"
"    \"ts-mocha\": \"^10.0.0\",\n"
"    \"typescript\": \"^5.3.0\",\n"
"    \"@types/chai\": \"^4.3.11\",\n"
"    \"@types/mocha\": \"^10.0.6\",\n"
"    \"@types/node\": \"^20.0.0\"\n"
"  }\n"
"}\n";

static const char *TPL_TSCONFIG_JSON =
"{\n"
"  \"compilerOptions\": {\n"
"    \"target\": \"ES2020\",\n"
"    \"module\": \"commonjs\",\n"
"    \"strict\": true,\n"
"    \"esModuleInterop\": true,\n"
"    \"resolveJsonModule\": true,\n"
"    \"skipLibCheck\": true,\n"
"    \"outDir\": \"./dist\"\n"
"  },\n"
"  \"include\": [\"./*.test.ts\"]\n"
"}\n";

static const char *TPL_TEST_TS =
"import { expect } from \"chai\";\n"
"import { LiteSVM } from \"litesvm\";\n"
"import {\n"
"  Keypair,\n"
"  PublicKey,\n"
"  Transaction,\n"
"  TransactionInstruction,\n"
"  SystemProgram,\n"
"} from \"@solana/web3.js\";\n"
"import * as fs from \"fs\";\n"
"import * as path from \"path\";\n"
"\n"
"describe(\"%s\", () => {\n"
"  const programPath = path.join(__dirname, \"..\", \"build\", \"program.so\");\n"
"  const programId = Keypair.generate().publicKey;\n"
"\n"
"  let svm: LiteSVM;\n"
"  let payer: Keypair;\n"
"\n"
"  before(() => {\n"
"    svm = new LiteSVM();\n"
"    svm.addProgram(programId, fs.readFileSync(programPath));\n"
"\n"
"    payer = Keypair.generate();\n"
"    svm.airdrop(payer.publicKey, BigInt(10_000_000_000));\n"
"  });\n"
"\n"
"  it(\"initializes the program\", () => {\n"
"    const counter = Keypair.generate();\n"
"\n"
"    const data = Buffer.alloc(1);\n"
"    data.writeUInt8(0, 0); // discriminator = 0\n"
"\n"
"    const ix = new TransactionInstruction({\n"
"      keys: [\n"
"        { pubkey: payer.publicKey, isSigner: true, isWritable: true },\n"
"        { pubkey: counter.publicKey, isSigner: true, isWritable: true },\n"
"        { pubkey: SystemProgram.programId, isSigner: false, isWritable: false },\n"
"      ],\n"
"      programId,\n"
"      data,\n"
"    });\n"
"\n"
"    const tx = new Transaction().add(ix);\n"
"    tx.recentBlockhash = svm.latestBlockhash();\n"
"    tx.sign(payer, counter);\n"
"\n"
"    svm.sendTransaction(tx);\n"
"\n"
"    const account = svm.getAccount(counter.publicKey);\n"
"    expect(account).to.not.be.null;\n"
"  });\n"
"});\n";

#endif /* CVL_TPL_TEST_H */
