#ifndef TPL_TEST_H
#define TPL_TEST_H

static const char *TPL_PACKAGE_JSON =
"{\n"
"  \"name\": \"%s-tests\",\n"
"  \"version\": \"1.0.0\",\n"
"  \"scripts\": {\n"
"    \"test\": \"npx ts-mocha -p tsconfig.json ./*.test.ts\"\n"
"  },\n"
"  \"dependencies\": {\n"
"    \"@solana/kit\": \"^6.5.0\",\n"
"    \"@types/chai\": \"^4.3.0\",\n"
"    \"@types/mocha\": \"^10.0.0\",\n"
"    \"@types/node\": \"^20.0.0\",\n"
"    \"chai\": \"^4.3.0\",\n"
"    \"litesvm\": \"^1.0.0\",\n"
"    \"mocha\": \"^10.0.0\",\n"
"    \"ts-mocha\": \"^10.0.0\",\n"
"    \"typescript\": \"^5.0.0\"\n"
"  }\n"
"}\n";

static const char *TPL_TSCONFIG_JSON =
"{\n"
"  \"compilerOptions\": {\n"
"    \"target\": \"ES2020\",\n"
"    \"module\": \"commonjs\",\n"
"    \"strict\": true,\n"
"    \"esModuleInterop\": true,\n"
"    \"resolveJsonModule\": true,\n"
"    \"skipLibCheck\": true,\n"
"    \"outDir\": \"./dist\"\n"
"  },\n"
"  \"include\": [\"./*.test.ts\"]\n"
"}\n";

static const char *TPL_TEST_TS =
"import { expect } from \"chai\";\n"
"import { LiteSVM, FailedTransactionMetadata } from \"litesvm\";\n"
"import {\n"
"  AccountRole,\n"
"  address,\n"
"  type Address,\n"
"  appendTransactionMessageInstruction,\n"
"  compileTransaction,\n"
"  createTransactionMessage,\n"
"  generateKeyPair,\n"
"  getAddressFromPublicKey,\n"
"  lamports,\n"
"  pipe,\n"
"  setTransactionMessageFeePayer,\n"
"  signTransaction,\n"
"  type Instruction,\n"
"  type Transaction,\n"
"} from \"@solana/kit\";\n"
"import * as fs from \"fs\";\n"
"import * as path from \"path\";\n"
"import { fileURLToPath } from \"url\";\n"
"const __dirname = path.dirname(fileURLToPath(import.meta.url));\n"
"\n"
"const SYSTEM_PROGRAM = address(\"11111111111111111111111111111111\");\n"
"\n"
"async function buildTx(\n"
"  svm: LiteSVM,\n"
"  feePayer: Address,\n"
"  signerKeys: CryptoKeyPair[],\n"
"  ix: Instruction,\n"
"): Promise<Transaction> {\n"
"  const msg = pipe(\n"
"    createTransactionMessage({ version: \"legacy\" }),\n"
"    (m) => setTransactionMessageFeePayer(feePayer, m),\n"
"    (m) => svm.setTransactionMessageLifetimeUsingLatestBlockhash(m),\n"
"    (m) => appendTransactionMessageInstruction(ix, m),\n"
"  );\n"
"  return await signTransaction(signerKeys, compileTransaction(msg));\n"
"}\n"
"\n"
"describe(\"%s\", () => {\n"
"  const programPath = path.join(__dirname, \"..\", \"build\", \"program.so\");\n"
"\n"
"  let programId: Address;\n"
"  let svm: LiteSVM;\n"
"  let payerKeys: CryptoKeyPair;\n"
"  let payerAddr: Address;\n"
"  let counterKeys: CryptoKeyPair;\n"
"  let counterAddr: Address;\n"
"\n"
"  before(async () => {\n"
"    const programKeys = await generateKeyPair();\n"
"    programId = await getAddressFromPublicKey(programKeys.publicKey);\n"
"\n"
"    svm = new LiteSVM();\n"
"    svm.addProgram(programId, fs.readFileSync(programPath));\n"
"\n"
"    payerKeys = await generateKeyPair();\n"
"    payerAddr = await getAddressFromPublicKey(payerKeys.publicKey);\n"
"    svm.airdrop(payerAddr, lamports(10_000_000_000n));\n"
"\n"
"    counterKeys = await generateKeyPair();\n"
"    counterAddr = await getAddressFromPublicKey(counterKeys.publicKey);\n"
"  });\n"
"\n"
"  it(\"initializes the program\", async () => {\n"
"    const ix: Instruction = {\n"
"      programAddress: programId,\n"
"      accounts: [\n"
"        { address: payerAddr, role: AccountRole.WRITABLE_SIGNER },\n"
"        { address: counterAddr, role: AccountRole.WRITABLE_SIGNER },\n"
"        { address: SYSTEM_PROGRAM, role: AccountRole.READONLY },\n"
"      ],\n"
"      data: new Uint8Array([0]),\n"
"    };\n"
"\n"
"    const tx = await buildTx(svm, payerAddr, [payerKeys, counterKeys], ix);\n"
"    const result = svm.sendTransaction(tx);\n"
"    if (result instanceof FailedTransactionMetadata)\n"
"      throw new Error(`Transaction failed: ${result.toString()}`);\n"
"\n"
"    const account = svm.getAccount(counterAddr);\n"
"    expect(account.exists).to.be.true;\n"
"  });\n"
"});\n";

#endif /* TPL_TEST_H */
