/* Code generated by quasar. DO NOT EDIT. */
#ifndef QUASAR_MULTISIG_CLIENT_H
#define QUASAR_MULTISIG_CLIENT_H

#include <caravel.h>

static const Pubkey QUASAR_MULTISIG_PROGRAM_ID = {{
    0x2d, 0x5b, 0x41, 0x3c, 0x65, 0x40, 0xde, 0x15, 
    0x0c, 0x93, 0x73, 0x14, 0x4d, 0x51, 0x33, 0xca, 
    0x4c, 0xb8, 0x30, 0xba, 0x0f, 0x75, 0x67, 0x16, 
    0xac, 0xea, 0x0e, 0x50, 0xd7, 0x94, 0x35, 0xe5
}};

static const uint8_t QUASAR_MULTISIG_CREATE_DISC[] = {0x00};
static const uint8_t QUASAR_MULTISIG_DEPOSIT_DISC[] = {0x01};
static const uint8_t QUASAR_MULTISIG_SET_LABEL_DISC[] = {0x02};
static const uint8_t QUASAR_MULTISIG_EXECUTE_TRANSFER_DISC[] = {0x03};

static const uint8_t QUASAR_MULTISIG_MULTISIG_CONFIG_ACCOUNT_DISC[] = {0x01};

typedef struct {
    Pubkey creator;
    uint8_t threshold;
    uint8_t bump;
    uint8_t * label;
    uint8_t * signers;
} quasar_multisig_multisig_config_t;

static inline void quasar_multisig_multisig_config_decode(
    const uint8_t *data, quasar_multisig_multisig_config_t *out
) {
    uint64_t offset = 0;
    for (int i = 0; i < 32; i++) out->creator.bytes[i] = data[offset + i]; offset += 32;
    out->threshold = data[offset]; offset += 1;
    out->bump = data[offset]; offset += 1;
    { uint8_t slen = data[offset]; offset += 1; offset += slen; }
    { uint16_t vlen = (uint16_t)data[offset] | ((uint16_t)data[offset+1] << 8); offset += 2; offset += vlen; }
}

typedef struct {
    Pubkey *creator;
    Pubkey *rent;
    Pubkey *systemProgram;
} quasar_multisig_create_accounts_t;

typedef struct {
    uint8_t threshold;
} quasar_multisig_create_args_t;

static inline uint64_t quasar_multisig_create_ix(
    quasar_multisig_create_accounts_t *accounts,
    quasar_multisig_create_args_t *args,
    const AccountMeta *remaining,
    uint64_t remaining_len,
    Instruction *ix_out,
    AccountMeta *meta_buf,
    uint8_t *data_buf,
    uint64_t data_buf_len
) {
    Pubkey pda_keys[1];
    {
        SignerSeed seeds[2];
        { static const uint8_t s[] = {0x6d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67}; seeds[0].addr = s; seeds[0].len = 8; }
        seeds[1].addr = accounts->creator->bytes; seeds[1].len = 32;
        uint8_t bump;
        find_program_address(seeds, 2, (Pubkey *)&QUASAR_MULTISIG_PROGRAM_ID, &pda_keys[0], &bump);
    }
    meta_buf[0] = meta_writable_signer(accounts->creator);
    meta_buf[1] = meta_writable(&pda_keys[0]);
    meta_buf[2] = meta_readonly(accounts->rent);
    meta_buf[3] = meta_readonly(accounts->systemProgram);
    uint64_t off = 0;
    if (data_buf_len < 1) return 0;
    for (uint64_t i = 0; i < 1; i++) data_buf[off++] = QUASAR_MULTISIG_CREATE_DISC[i];
    data_buf[off++] = args->threshold;
    for (uint64_t i = 0; i < remaining_len; i++) meta_buf[4 + i] = remaining[i];
    ix_out->program_id = (Pubkey *)&QUASAR_MULTISIG_PROGRAM_ID;
    ix_out->accounts = meta_buf;
    ix_out->accounts_len = 4 + remaining_len;
    ix_out->data = data_buf;
    ix_out->data_len = off;
    return off;
}

typedef struct {
    Pubkey *depositor;
    Pubkey *config;
    Pubkey *systemProgram;
} quasar_multisig_deposit_accounts_t;

typedef struct {
    uint64_t amount;
} quasar_multisig_deposit_args_t;

static inline uint64_t quasar_multisig_deposit_ix(
    quasar_multisig_deposit_accounts_t *accounts,
    quasar_multisig_deposit_args_t *args,
    Instruction *ix_out,
    AccountMeta *meta_buf,
    uint8_t *data_buf,
    uint64_t data_buf_len
) {
    Pubkey pda_keys[1];
    {
        SignerSeed seeds[2];
        { static const uint8_t s[] = {0x76, 0x61, 0x75, 0x6c, 0x74}; seeds[0].addr = s; seeds[0].len = 5; }
        seeds[1].addr = accounts->config->bytes; seeds[1].len = 32;
        uint8_t bump;
        find_program_address(seeds, 2, (Pubkey *)&QUASAR_MULTISIG_PROGRAM_ID, &pda_keys[0], &bump);
    }
    meta_buf[0] = meta_writable_signer(accounts->depositor);
    meta_buf[1] = meta_readonly(accounts->config);
    meta_buf[2] = meta_writable(&pda_keys[0]);
    meta_buf[3] = meta_readonly(accounts->systemProgram);
    uint64_t off = 0;
    if (data_buf_len < 1) return 0;
    for (uint64_t i = 0; i < 1; i++) data_buf[off++] = QUASAR_MULTISIG_DEPOSIT_DISC[i];
    { uint64_t v = args->amount; for (int i = 0; i < 8; i++) { data_buf[off + i] = (uint8_t)(v >> (i * 8)); } off += 8; }
    ix_out->program_id = (Pubkey *)&QUASAR_MULTISIG_PROGRAM_ID;
    ix_out->accounts = meta_buf;
    ix_out->accounts_len = 4;
    ix_out->data = data_buf;
    ix_out->data_len = off;
    return off;
}

typedef struct {
    Pubkey *creator;
    Pubkey *systemProgram;
} quasar_multisig_set_label_accounts_t;

typedef struct {
    uint8_t * label;
} quasar_multisig_set_label_args_t;

static inline uint64_t quasar_multisig_set_label_ix(
    quasar_multisig_set_label_accounts_t *accounts,
    quasar_multisig_set_label_args_t *args,
    Instruction *ix_out,
    AccountMeta *meta_buf,
    uint8_t *data_buf,
    uint64_t data_buf_len
) {
    Pubkey pda_keys[1];
    {
        SignerSeed seeds[2];
        { static const uint8_t s[] = {0x6d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67}; seeds[0].addr = s; seeds[0].len = 8; }
        seeds[1].addr = accounts->creator->bytes; seeds[1].len = 32;
        uint8_t bump;
        find_program_address(seeds, 2, (Pubkey *)&QUASAR_MULTISIG_PROGRAM_ID, &pda_keys[0], &bump);
    }
    meta_buf[0] = meta_writable_signer(accounts->creator);
    meta_buf[1] = meta_writable(&pda_keys[0]);
    meta_buf[2] = meta_readonly(accounts->systemProgram);
    uint64_t off = 0;
    if (data_buf_len < 1) return 0;
    for (uint64_t i = 0; i < 1; i++) data_buf[off++] = QUASAR_MULTISIG_SET_LABEL_DISC[i];
    /* DynString not directly serializable in C without length info */
    ix_out->program_id = (Pubkey *)&QUASAR_MULTISIG_PROGRAM_ID;
    ix_out->accounts = meta_buf;
    ix_out->accounts_len = 3;
    ix_out->data = data_buf;
    ix_out->data_len = off;
    return off;
}

typedef struct {
    Pubkey *creator;
    Pubkey *recipient;
    Pubkey *systemProgram;
} quasar_multisig_execute_transfer_accounts_t;

typedef struct {
    uint64_t amount;
} quasar_multisig_execute_transfer_args_t;

static inline uint64_t quasar_multisig_execute_transfer_ix(
    quasar_multisig_execute_transfer_accounts_t *accounts,
    quasar_multisig_execute_transfer_args_t *args,
    const AccountMeta *remaining,
    uint64_t remaining_len,
    Instruction *ix_out,
    AccountMeta *meta_buf,
    uint8_t *data_buf,
    uint64_t data_buf_len
) {
    Pubkey pda_keys[2];
    {
        SignerSeed seeds[2];
        { static const uint8_t s[] = {0x6d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67}; seeds[0].addr = s; seeds[0].len = 8; }
        seeds[1].addr = accounts->creator->bytes; seeds[1].len = 32;
        uint8_t bump;
        find_program_address(seeds, 2, (Pubkey *)&QUASAR_MULTISIG_PROGRAM_ID, &pda_keys[0], &bump);
    }
    {
        SignerSeed seeds[2];
        { static const uint8_t s[] = {0x76, 0x61, 0x75, 0x6c, 0x74}; seeds[0].addr = s; seeds[0].len = 5; }
        seeds[1].addr = pda_keys[0].bytes; seeds[1].len = 32;
        uint8_t bump;
        find_program_address(seeds, 2, (Pubkey *)&QUASAR_MULTISIG_PROGRAM_ID, &pda_keys[1], &bump);
    }
    meta_buf[0] = meta_readonly(&pda_keys[0]);
    meta_buf[1] = meta_readonly(accounts->creator);
    meta_buf[2] = meta_writable(&pda_keys[1]);
    meta_buf[3] = meta_writable(accounts->recipient);
    meta_buf[4] = meta_readonly(accounts->systemProgram);
    uint64_t off = 0;
    if (data_buf_len < 1) return 0;
    for (uint64_t i = 0; i < 1; i++) data_buf[off++] = QUASAR_MULTISIG_EXECUTE_TRANSFER_DISC[i];
    { uint64_t v = args->amount; for (int i = 0; i < 8; i++) { data_buf[off + i] = (uint8_t)(v >> (i * 8)); } off += 8; }
    for (uint64_t i = 0; i < remaining_len; i++) meta_buf[5 + i] = remaining[i];
    ix_out->program_id = (Pubkey *)&QUASAR_MULTISIG_PROGRAM_ID;
    ix_out->accounts = meta_buf;
    ix_out->accounts_len = 5 + remaining_len;
    ix_out->data = data_buf;
    ix_out->data_len = off;
    return off;
}

#endif /* QUASAR_MULTISIG_CLIENT_H */
